server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: TalkNativeBackend
  datasource:
    url: jdbc:mysql://localhost:3306/talknative
    username: root
    password: wulin9786
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Load API key from environment variable

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.MySQL8Dialect
