server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: TalkNativeBackend
  datasource:
    url: jdbc:mysql://db-talknative.cb0q2a4g4xfp.us-east-1.rds.amazonaws.com:3306/talknative?useSSL=false&serverTimezone=UTC
    username: root
    password: wulin9786
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      api-key: ${OPENAI_API_KEY} # Load API key from environment variable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
